### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by WortJohn** [OpenGene/MutScan#4]
When i compile it, the error arises.

> $make

> g++ -std=c++11 -g -Wall -I./inc -O3 -c  src/common.cpp -o obj/common.o

> cc1plus: error：Unable to identify the command-line options“-std=c++11”

> make: *** [obj/common.o] error 1

**Comment by sfchen** [comment]
seems that your compiler doesn't support c++11.

could you let me know your system and g++ version?

**Comment by WortJohn** [comment]
Ok!

>$ lsb_release -a

> LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch

> Distributor ID:	CentOS

> Description:	CentOS release 6.6 (Final)

> Release:	6.6

> Codename:	Final

> $g++ --version

> g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by sfchen** [comment]
Your gcc is too old that it has no c++ 11 support. You need gcc 4.7 at least.

Can you upgrade gcc to later version, or shall I provide a pre-built binary `MutScan` so that you can download and use it without compile?

**Comment by sfchen** [comment]
I uploaded one executable binary (compiled with Ubuntu, but should work on Cent OS). Could you please try:
```shell
wget http://opengene.org/MutScan/linux/mutscan
chmod a+x ./mutscan
```
Then use `./mutscan`?

**Comment by sfchen** [comment]
@WortJohn any update?

**Comment by sfchen** [comment]
@WortJohn could you please download `http://opengene.org/MutScan/linux/mutscan` and test whether it works?

I'd like to provide regular prebuilt binaries for future releases.

**Comment by WortJohn** [comment]
@sfchen I am sorry to reply to you so later. I test it and it shows **"./mutscan:
 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./mutscan)" and "./mutscan: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./mutscan)"** . I know the version of "glibc" is low and download the high version from the website "https://www.gnu.org/software/libc/", but it is not okay. After updating it, it influences frequently-used command of linux, so i don't know why it is . I am not be familiar with C++, so i don't know how to solve it.
