### ISSUE TITLE
About VCF format

### ISSUE THREAD

**Issue by biofer** [OpenGene/MutScan#5]
`../mutscan -1 R1.fq.gz -2 R2.fq.gz -r tinyref.fa -m tinyvcf.vcf`
No mutation to be scanned
Your VCF contains no valid records

**Comment by sfchen** [comment]
I will test and update.

**Comment by sfchen** [comment]
This is because tinyref.fa only has only few bases, and tinyvcf.vcf is a real VCF based on hg19.

You can try:

`../mutscan -1 R1.fq.gz -2 R2.fq.gz -r hg19.fasta -m tinyvcf.vcf`
