### ISSUE TITLE
HTML report can't work while copy it to windows, and may be a output directory needed.

### ISSUE THREAD

**Issue by qins** [OpenGene/MutScan#6]
As main html file(coloRectS2.mutscan.html)'s code show:
`src='/home/foo/Work/Project/bar/coloRectS2.mutscan.html.files/index.html'`

So, I can only use current directory as output directory?

Could you trim the header of the html report file path in main html's src code?

Thanks!

**Comment by sfchen** [comment]
You should copy `xxxx.html`, along with the folder `xxxx.html.files`, they should be kept together

**Comment by qins** [comment]
Yeah, they were kept together. Like this?
![1](https://user-images.githubusercontent.com/3041080/34294170-3657ce04-e742-11e7-9da6-2d9787ff17b1.png)

And I found the html kept linux's file path, it will be fine if only file names left.
![2](https://user-images.githubusercontent.com/3041080/34294197-62ff1dea-e742-11e7-8877-fb7fd201c275.png)

Thanks for the quick reply~

**Comment by sfchen** [comment]
I see, I will fix this issue in future version.

Thanks.

**Comment by sfchen** [comment]
This is fixed.

Can you try the latest code by git?

**Comment by qins** [comment]
It works like a charm ;D

**Comment by qins** [comment]
Sorry, I tested it in current path. So did not find the html folder's wrong path in Linux which is fixed in current path, not with mutscan.html's full path

**Comment by sfchen** [comment]
Did you mean this bug is still not fixed?

**Comment by qins** [comment]
Yes. The mFolderName is not in the same path with mFilename.

>  mkdir(mFolderName.c_str(), 0777);

**Comment by sfchen** [comment]
Thanks, I see, I will fix it in minutes

**Comment by sfchen** [comment]
Just fixed it, could you try the latest code again?

Thanks for your testing.

**Comment by qins** [comment]
Solved.
Appreciate your awesome work!

**Comment by sfchen** [comment]
Great, closing...
