### ISSUE TITLE
Manuscript/Preprint?

### ISSUE THREAD

**Issue by dnbaker** [OpenGene/MutScan#7]
Hi,

Do you have a manuscript describing the method? I'd prefer to read about how it works rather than dig directly into the code if possible. And it seems that [this manuscript](https://www.researchgate.net/publication/2884978_MutScan_A_Fourier_Based_Method_For_the_Identification_of) is entirely unrelated.

Thank you!

**Comment by sfchen** [comment]
The paper of MutScan was just accepted by BMC Bioinformatics, and may be online soon. I will let you know once it's there

**Comment by sfchen** [comment]
See:

Shifu Chen, Tanxiao Huang, TieXiang Wen, Hong Li, Mingyan Xu and Jia Gu. MutScan: fast detection and visualization of target mutations by scanning FASTQ data. BMC Bioinformatics. https://doi.org/10.1186/s12859-018-2024-6
